"use client";

import { FormEvent, useMemo, useState } from "react";
import Link from "next/link";

const steps = ["Participant", "Participation", "Details", "Review", "Payment"];
type FormState = { name:string; email:string; mobile:string; municipality:string; organization:string; category:string; participation:string; bamboo:number; notes:string };
const initial: FormState = { name:"", email:"", mobile:"", municipality:"", organization:"", category:"Individual", participation:"Celebration participant", bamboo:1, notes:"" };

export default function RegisterPage() {
  const [step,setStep] = useState(0);
  const [form,setForm] = useState<FormState>(initial);
  const [paymentState,setPaymentState] = useState<"idle"|"verifying"|"success"|"failed"|"pending">("idle");
  const reference = "WBD26-DEMO-00421";
  function update<K extends keyof FormState>(key:K,value:FormState[K]) { setForm((current)=>({ ...current,[key]:value })); }
  function next(event?:FormEvent) { event?.preventDefault(); setStep((current)=>Math.min(current+1,steps.length-1)); }
  function back() { setStep((current)=>Math.max(current-1,0)); }
  const completed = useMemo(()=>paymentState==="success",[paymentState]);

  if (completed) return <main className="shell registration-shell"><div className="registration-success"><span className="eyebrow">REGISTRATION CONFIRMED · DEMO</span><h1>You&apos;re part of World Bamboo Day 2026.</h1><p>This is a simulated confirmation. No personal data or payment was transmitted.</p><div className="confirmation-grid"><div><span>REFERENCE</span><strong>{reference}</strong></div><div><span>EVENT</span><strong>18 September 2026 · Loboc, Bohol</strong></div></div><DemoQr label="EVENT CHECK-IN QR" /><p className="microcopy center">This demo QR illustrates event admission. It is not a payment QR.</p><div className="hero-actions center"><Link href="/" className="button quiet">Return home</Link><button className="button primary" onClick={()=>{setStep(0);setForm(initial);setPaymentState("idle");}}>Restart demo</button></div></div></main>;

  return <main className="shell registration-shell">
    <div className="registration-intro"><span className="eyebrow">04 — REGISTRATION PROTOTYPE</span><h1>One clear registration journey.</h1><p>No real registration or payment occurs in this prototype. Fields and participation mechanics remain subject to organizer approval.</p></div>
    <div className="stepper">{steps.map((label,i)=><div key={label} className={i===step?"current":i<step?"done":""}><span>{String(i+1).padStart(2,"0")}</span><strong>{label}</strong></div>)}</div>
    <div className="wizard-panel">
      {step===0 && <form onSubmit={next}><WizardHead number="01" title="Participant" text="Tell us who will participate." /><div className="form-grid"><Field label="Full name *"><input required value={form.name} onChange={(e)=>update("name",e.target.value)} placeholder="Juan Dela Cruz" /></Field><Field label="Email address *"><input required type="email" value={form.email} onChange={(e)=>update("email",e.target.value)} placeholder="juan@example.com" /></Field><Field label="Mobile number *"><input required value={form.mobile} onChange={(e)=>update("mobile",e.target.value)} placeholder="09XX XXX XXXX" /></Field><Field label="Municipality / City *"><input required value={form.municipality} onChange={(e)=>update("municipality",e.target.value)} placeholder="Loboc, Bohol" /></Field><Field label="Organization / Affiliation"><input value={form.organization} onChange={(e)=>update("organization",e.target.value)} placeholder="Optional" /></Field><Field label="Participant category"><select value={form.category} onChange={(e)=>update("category",e.target.value)}>{["Individual","Student","Government","Private Sector","NGO / Civic Organization","Bamboo Grower","Bamboo Enterprise","Volunteer","Other"].map((x)=><option key={x}>{x}</option>)}</select></Field></div><WizardActions nextLabel="Continue to participation →" /></form>}
      {step===1 && <div><WizardHead number="02" title="Participation" text="Choose the proposed way you will take part." /><div className="choice-list">{[["Celebration participant","Register as an individual participant in the World Bamboo Day activities."],["Bamboo commitment","Indicate one or more bamboo planting units to support or participate with."],["Organization / delegation","Register participation under an organization or group. Bulk registration is not yet in MVP."]].map(([title,text])=><button key={title} className={form.participation===title?"selected":""} onClick={()=>update("participation",title)}><span>{form.participation===title?"●":"○"}</span><div><strong>{title}</strong><p>{text}</p></div><em>PROPOSED</em></button>)}</div>{form.participation==="Bamboo commitment" && <div className="quantity-row"><div><span className="eyebrow">BAMBOO UNITS</span><strong>Proposed quantity</strong></div><div><button onClick={()=>update("bamboo",Math.max(1,form.bamboo-1))}>−</button><b>{form.bamboo}</b><button onClick={()=>update("bamboo",form.bamboo+1)}>+</button></div></div>}<WizardActions onBack={back} onNext={()=>next()} nextLabel="Continue to details →" /></div>}
      {step===2 && <div><WizardHead number="03" title="Event details" text="Only operationally necessary fields should survive discovery." /><div className="form-grid"><Field label="Preferred activity / batch"><select disabled><option>To be confirmed</option></select></Field><Field label="Transportation requirement"><select disabled><option>To be confirmed</option></select></Field><Field label="Accessibility / operational note"><textarea value={form.notes} onChange={(e)=>update("notes",e.target.value)} placeholder="Optional — only if relevant to event operations" /></Field></div><div className="proposal-callout"><span>PRIVACY-BY-DESIGN NOTE</span><p>These are proposal placeholders. Organizers should identify which information is genuinely necessary before production.</p></div><WizardActions onBack={back} onNext={()=>next()} nextLabel="Review registration →" /></div>}
      {step===3 && <div><WizardHead number="04" title="Review" text="Confirm the participant record before initiating payment." /><div className="review-sheet"><ReviewRow label="Participant" value={form.name||"Demo participant"} /><ReviewRow label="Mobile" value={form.mobile||"09XX XXX XXXX"} /><ReviewRow label="Municipality" value={form.municipality||"Loboc, Bohol"} /><ReviewRow label="Affiliation" value={form.organization||"—"} /><ReviewRow label="Participation" value={form.participation} /><ReviewRow label="Bamboo commitment" value={form.participation==="Bamboo commitment"?`${form.bamboo} unit(s)`:"Not selected"} /><ReviewRow label="Amount due" value="TO BE CONFIRMED" status="OPEN" /></div><div className="check-list"><label><input type="checkbox" defaultChecked /> Information above is correct for this demo.</label><label><input type="checkbox" defaultChecked /> I acknowledge the proposed participation guidelines.</label><label><input type="checkbox" defaultChecked /> I have reviewed the prototype privacy note.</label></div><WizardActions onBack={back} onNext={()=>next()} nextLabel="Continue to payment →" /></div>}
      {step===4 && <div><WizardHead number="05" title="Payment preview" text="Simulate the proposed approved-payment experience." /><div className="payment-summary"><div><span>REGISTRATION</span><strong>{reference}</strong></div><div><span>AMOUNT DUE</span><strong>TO BE CONFIRMED</strong></div><div><span>STATUS</span><strong>{paymentState==="idle"?"AWAITING PAYMENT":paymentState.toUpperCase()}</strong></div></div><div className="payment-methods"><button className="selected"><strong>QR PH</strong><span>Preferred automated flow</span></button><button><strong>GCASH</strong><span>Provider redirect / hosted checkout</span></button><button><strong>MAYA</strong><span>Provider redirect / hosted checkout</span></button><button><strong>MANUAL</strong><span>Institutional fallback</span></button></div><div className="qr-payment"><DemoQr label="DEMO / NOT PAYABLE" /><div><span className="eyebrow">QR PH PAYMENT PREVIEW</span><h3>Scan in production. Not payable here.</h3><p>The production provider would generate a transaction-specific QR or hosted payment session. This prototype deliberately contains no payable payload.</p><div className="demo-controls"><button onClick={()=>{setPaymentState("verifying");setTimeout(()=>setPaymentState("success"),900);}}>Simulate success</button><button onClick={()=>setPaymentState("pending")}>Simulate pending</button><button onClick={()=>setPaymentState("failed")}>Simulate failed</button></div></div></div><WizardActions onBack={back} /></div>}
    </div>
  </main>;
}

function WizardHead({number,title,text}:{number:string;title:string;text:string}) { return <div className="wizard-head"><span>{number}</span><div><h2>{title}</h2><p>{text}</p></div></div>; }
function Field({label,children}:{label:string;children:React.ReactNode}) { return <label className="field"><span>{label}</span>{children}</label>; }
function WizardActions({onBack,onNext,nextLabel}:{onBack?:()=>void;onNext?:()=>void;nextLabel?:string}) { return <div className="wizard-actions">{onBack?<button type="button" className="button quiet" onClick={onBack}>← Back</button>:<span />}{nextLabel&&<button type={onNext?"button":"submit"} className="button primary" onClick={onNext}>{nextLabel}</button>}</div>; }
function ReviewRow({label,value,status}:{label:string;value:string;status?:string}) { return <div><span>{label}</span><strong>{value}</strong>{status&&<em data-status={status}>{status}</em>}</div>; }
function DemoQr({label}:{label:string}) { return <div className="demo-qr" aria-label={label}><div className="qr-pattern" /><span>{label}</span></div>; }
